### ISSUE TITLE
gcc9 multiple -Wdeprecated-copy warnings

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITK#1302]
Compiling with gcc 9.1.0 generates a lot of -Wdeprecated-copy warnings.

A nice explanation on why and how to solve these warnings can be find here: https://github.com/intel/tbb/issues/161

> There are two types of causes for -Wdeprecated-copy warnings
> 1. An assignment operator is written without a copy constructor, or a copy constructor is written without an assignment operator
> 2. An assignment operator or copy constructor is made private without defining the other

A warning example:
```
Modules/Core/Common/include/itkVectorContainer.h:195:5: note: because ‘itk::VectorContainer<long unsigned int, itk::Point<double, 4> >::Iterator’ has user-provided ‘itk::VectorContainer<TElementIdentifier, TElement>::Iterator::Iterator(const itk::VectorContainer<TElementIdentifier, TElement>::Iterator&) [with TElementIdentifier = long unsigned int; TElement = itk::Point<double, 4>]’
  195 |     Iterator(const Iterator & r)
      |     ^~~~~~~~
Modules/Core/Transform/test/itkSplineKernelTransformTest.cxx:544:71: warning: implicitly-declared ‘itk::VectorContainer<long unsigned int, itk::Point<double, 4> >::Iterator& itk::VectorContainer<long unsigned int, itk::Point<double, 4> >::Iterator::operator=(const itk::VectorContainer<long unsigned int, itk::Point<double, 4> >::Iterator&)’ is deprecated [-Wdeprecated-copy]
  544 |   tps4DsEnd = tps4D->GetModifiableSourceLandmarks()->GetPoints()->End();
      |                                                                       ^
In file included from Modules/Core/Common/include/itkDefaultStaticMeshTraits.h:22,
                 from Modules/Core/Common/include/itkPointSet.h:32,
                 from Modules/Core/Transform/include/itkKernelTransform.h:23,
                 from Modules/Core/Transform/include/itkElasticBodySplineKernelTransform.h:21,
                 from Modules/Core/Transform/test/itkSplineKernelTransformTest.cxx:25:
Modules/Core/Common/include/itkVectorContainer.h:195:5: note: because ‘itk::VectorContainer<long unsigned int, itk::Point<double, 4> >::Iterator’ has user-provided ‘itk::VectorContainer<TElementIdentifier, TElement>::Iterator::Iterator(const itk::VectorContainer<TElementIdentifier, TElement>::Iterator&) [with TElementIdentifier = long unsigned int; TElement = itk::Point<double, 4>]’
  195 |     Iterator(const Iterator & r)
```

**Comment by DVigneault** [comment]
Just submitted PR #1839 which addresses these warnings in `itk::MapContainer` and `itk::VectorContainer`.  The following classes define `operator=` but do not define a copy constructor, and therefore are also giving me similar warnings:

```
itk::LineSpatialObjectPoint
itk::DTITubeSpatialObjectPoint
itk::SpatialObjectPoint
itk::ContourSpatialObjectPoint
itk::TubeSpatialObjectPoint
itk::SurfaceSpatialObjectPoint
itk::SpatialObjectProperty
```

These remain to be addressed, and therefore I ask that this issue remains open.

**Comment by phcerdan** [comment]
Working on it, thanks for that list.

**Comment by DVigneault** [comment]
@phcerdan Oh no!  I just saw this--I've just pushed another commit which (hopefully) resolves the SpatialObjects issues.  Hope you didn't spend too much time on it yet...

**Comment by phcerdan** [comment]
Oh not at all. Thank you for working on this. Commenting on your PR.

**Comment by DVigneault** [comment]
PR #1839 merged (thank you @thewtex!)--to my knowledge, that's resolves this issue for ITK proper--the remaining errors on recompiling are in third party libraries (`gdcm` and `H5`):

```
warning: implicitly-declared ‘gdcm::FileMetaInformation& gdcm::                      FileMetaInformation::operator=(const gdcm::FileMetaInformation&)’ is deprecated [-Wdeprecated-copy]
warning: implicitly-declared ‘H5::DataSet& H5::DataSet::operator=(const H5::DataSet&)’ is deprecated [-Wdeprecated-copy]
```

Are we good to close this, or should we wait until the above warnings have been resolved as well?

**Comment by thewtex** [comment]
@DVigneault @phcerdan awesome work on this!! Go team ITK!

I upgraded to GCC 9 / Ubuntu 20.04, and we still have the GDCM and HDF5 warnings:

https://open.cdash.org/viewBuildError.php?type=1&buildid=6933216

**Comment by dzenanz** [comment]
I think this has been fixed. If somebody disagrees, please reopen with an explanation.
