### ISSUE TITLE
ITK wheel 5.4.4 built with incorrect numpy specifications (on MacOS)

### ISSUE THREAD

**Issue by sharkovsky** [InsightSoftwareConsortium/ITK#5399]
### Description

Under some setups, ITK 5.4.4 gets installed alongside older versions of numpy (e.g. numpy 1.26.4), even though the `pyproject.toml` clearly states that `numpy = ">=2.1.2,<3"` is needed.

After some investigations, it seems to me that the wheel for itk 5.4.4 does not contain the correct metadata for specifying the numpy requirement. 

### Steps to Reproduce

1. `pip install "itk==5.4.4" "numpy==1.26.4"`
2. report wheel hash for reproducibility if needed 
```shell
cat /Users/fcremone/miniconda3/envs/test-pip-py311/lib/python3.11/site-packages/itk-5.4.4.dist-info/RECORD | grep WHEEL
itk-5.4.4.dist-info/WHEEL,sha256=hBXMl1zxmXcKeN79_BRTBh9A1lsoBtzvtj2D6A8k3KA,114
```
3. Verify incorrect metadata
```shell
cat /Users/fcremone/miniconda3/envs/test-pip-py311/lib/python3.11/site-packages/itk-5.4.4.dist-info/METADATA | grep numpy
Requires-Dist: numpy
```

### Expected behavior

Pip should complain that the two versions are not compatible. 

At step 3 above, the `Requires-Dist` should state the numpy version, not just generic numpy.

### Actual behavior

Pip happily installs the incompatible versions. When I try to import itk, I get the following error

```none
import itk
../.tox/py3.11/lib/python3.11/site-packages/itk/__init__.py:28: in <module>
    from itk.support.extras import *
../.tox/py3.11/lib/python3.11/site-packages/itk/support/extras.py:37: in <module>
    import itk.support.types as itkt
../.tox/py3.11/lib/python3.11/site-packages/itk/support/types.py:178: in <module>
    ) = itkCType.initialize_c_types_once()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.tox/py3.11/lib/python3.11/site-packages/itk/support/types.py:143: in initialize_c_types_once
    _B: "itkCType" = itkCType("bool", "B", np.dtype(np.bool))
                                                    ^^^^^^^
../.tox/py3.11/lib/python3.11/site-packages/numpy/__init__.py:324: in __getattr__
    raise AttributeError(__former_attrs__[attr])
E   AttributeError: module 'numpy' has no attribute 'bool'.
E   `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
E   The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E       https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

### Reproducibility

All the time on the same machine/environment. 

See above for a hash of the installed itk wheel. 

### Environment

Mac OS Sonoma 14.6.1 (M3 chip) (the issue is confirmed also on another MacOS CI machine, and potentially on other non-MacOS machines)
Python 3.11.13
itk 5.4.4

**Comment by thewtex** [comment]
@sharkovsky thanks for the report 🙏 

> E   AttributeError: module 'numpy' has no attribute 'bool'.
E   `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
E   The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E       https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

This is addressed in #5402

>  even though the pyproject.toml clearly states that numpy = ">=2.1.2,<3" is needed.

Where is the referenced pyproject.toml and dep?

**Comment by sharkovsky** [comment]
Thank you for your reply @thewtex . 

I agree that #5402 will fix the specific `AttributeError`, but isn't there still an issue with the fact that the incorrect version of numpy is being installed with ITK? 

This is the `pyprojet.toml` of itk v5.4.4:
https://github.com/InsightSoftwareConsortium/ITK/blob/f98d5fac5e1d5ef694f3010f12bbbc2c792994c6/pyproject.toml#L24

Unless I'm misinterpreting (which is possible), doesn't it mean that numpy>=2.1.2 is required by itk?

**Comment by sharkovsky** [comment]
Thank you @thewtex, sorry for getting confused between the development/testing and the production dependencies. It's all clear now. 

So if I understood correctly, the correct dependency is recent numpy 1.X, and #5402 solves a bug that prevented the use of the older numpy versions. 

If I understood correctly, you can close this issue.

> As a workaround for now, can you install NumPy 2?
Yes we can find a workaround, either pinning to a recent numpy or avoiding the itk versions which introduced the issue. 

Last question: did you "hot-patch" the itk 5.4.4. wheel to include #5402? Or will it be included in 5.4.5?

**Comment by thewtex** [comment]
@sharkovsky yes, we'll include the fix in ITK 5.4.5. Thanks again for the report!
